2020-12-17 01:27:45,429 INFO    MainThread:605750 [wandb_setup.py:_flush():70] setting env: {}
2020-12-17 01:27:45,429 INFO    MainThread:605750 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-17 01:27:45,429 INFO    MainThread:605750 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-17 01:27:45,429 INFO    MainThread:605750 [wandb_init.py:_log_setup():303] Logging user logs to /home/chaoyanghe/sourcecode/MiLeNAS/wandb/run-20201217_012745-3981q0sw/logs/debug.log
2020-12-17 01:27:45,429 INFO    MainThread:605750 [wandb_init.py:_log_setup():304] Logging internal logs to /home/chaoyanghe/sourcecode/MiLeNAS/wandb/run-20201217_012745-3981q0sw/logs/debug-internal.log
2020-12-17 01:27:46,337 INFO    MainThread:605750 [wandb_run.py:_console_start():1237] atexit reg
2020-12-17 01:27:46,338 INFO    MainThread:605750 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2020-12-17 01:27:46,339 INFO    MainThread:605750 [wandb_run.py:_redirect():1107] Redirecting console.
2020-12-17 01:27:46,339 INFO    MainThread:605750 [redirect.py:install():204] install start
2020-12-17 01:27:46,340 INFO    MainThread:605750 [redirect.py:install():219] install stop
2020-12-17 01:27:46,340 INFO    MainThread:605750 [redirect.py:install():204] install start
2020-12-17 01:27:46,340 INFO    MainThread:605750 [redirect.py:install():219] install stop
2020-12-17 01:27:46,340 INFO    MainThread:605750 [wandb_run.py:_redirect():1151] Redirects installed.
2020-12-17 01:27:50,150 INFO    MainThread:605750 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2020-12-17 01:27:50,150 INFO    MainThread:605750 [wandb_run.py:_restore():1179] restore
2020-12-17 01:27:50,150 INFO    MainThread:605750 [redirect.py:uninstall():223] uninstall start
2020-12-17 01:27:50,150 INFO    MainThread:605750 [redirect.py:_stop():278] _stop: stdout
2020-12-17 01:27:50,151 INFO    MainThread:605750 [redirect.py:_stop():284] _stop closed: stdout
2020-12-17 01:27:50,151 INFO    stdout    :605750 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-12-17 01:27:50,151 INFO    stdout    :605750 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:_stop():290] _stop joined: stdout
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:_stop():292] _stop rd closed: stdout
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:uninstall():227] uninstall done
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:uninstall():223] uninstall start
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:_stop():278] _stop: stderr
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:_stop():284] _stop closed: stderr
2020-12-17 01:27:50,152 INFO    stderr    :605750 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-12-17 01:27:50,152 INFO    stderr    :605750 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:_stop():290] _stop joined: stderr
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:_stop():292] _stop rd closed: stderr
2020-12-17 01:27:50,152 INFO    MainThread:605750 [redirect.py:uninstall():227] uninstall done
2020-12-17 01:27:50,155 INFO    MainThread:605750 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "22a20f09b73a4c75aede445d9ef23ba3"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 1431
      total_bytes: 1431
    }
  }
}

2020-12-17 01:27:52,160 INFO    MainThread:605750 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "712705a05037401a90d9de61c42e8b9a"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 7140
      total_bytes: 7140
    }
  }
}

2020-12-17 01:27:53,256 INFO    MainThread:605750 [wandb_run.py:_show_files():1536] logging synced files
2020-12-17 01:27:53,260 INFO    MainThread:605750 [internal.py:handle_exit():138] Internal process exited
